# Generated by Django 5.2.4 on 2026-01-08 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0007_inventoryitem_expected_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductIncentive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ASM_incentive', models.DecimalField(decimal_places=2, max_digits=10)),
                ('RSM_incentive', models.DecimalField(decimal_places=2, max_digits=10)),
                ('has_dynamic_price', models.BooleanField(default=False)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='incentive_price', to='inventory.inventoryitem')),
            ],
        ),
        migrations.CreateModel(
            name='ProductIncentiveTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_quantity', models.PositiveIntegerField()),
                ('ASM_incentive', models.DecimalField(decimal_places=2, max_digits=10)),
                ('RSM_incentive', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Product_Incentive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incentive_calculator.productincentive')),
            ],
        ),
    ]
