# Generated by Django 5.2.4 on 2026-04-07 05:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_dashboard', '0009_paymentdiscussionthread_paymentexpecteddatehistory_and_more'),
        ('incentive_calculator', '0001_initial'),
        ('inventory', '0007_inventoryitem_expected_quantity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncentiveCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('base_ASM_incentive', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('base_RSM_incentive', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Incentive Categories',
            },
        ),
        migrations.RemoveField(
            model_name='productincentive',
            name='ASM_incentive',
        ),
        migrations.RemoveField(
            model_name='productincentive',
            name='RSM_incentive',
        ),
        migrations.AddField(
            model_name='productincentive',
            name='asm_override',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productincentive',
            name='is_special_pack',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productincentive',
            name='msp',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='productincentive',
            name='pack_size_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='If pack of 5, set 5. If 5kg, set 5.', max_digits=10),
        ),
        migrations.AddField(
            model_name='productincentive',
            name='rsm_override',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='productincentive',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='incentive_config', to='inventory.inventoryitem'),
        ),
        migrations.AddField(
            model_name='productincentive',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='incentive_calculator.incentivecategory'),
        ),
        migrations.CreateModel(
            name='IncentivePaymentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid_to_asm', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('amount_frozen', models.DecimalField(decimal_places=2, max_digits=14)),
                ('paid_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('voucher_status', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='incentive_payout_record', to='customer_dashboard.customervoucherstatus')),
            ],
            options={
                'verbose_name': 'Incentive Payment Status',
            },
        ),
    ]
