# Generated by Django 5.2.4 on 2026-07-10 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_dashboard', '0011_alter_customercreditprofile_credit_period_days'),
        ('incentive_calculator', '0002_incentivecategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerIncentiveTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='incentive_trigger', to='customer_dashboard.customer')),
            ],
        ),
    ]
