# Generated by Django 5.2.4 on 2025-12-09 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_dashboard', '0002_customer_latitude_customer_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesperson',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to='customer_dashboard.salesperson'),
        ),
    ]
