# Generated by Django 5.2.4 on 2026-06-22 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_dashboard', '0010_customerunit_customerunitmembership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercreditprofile',
            name='credit_period_days',
            field=models.PositiveIntegerField(default=7),
        ),
    ]
