# Generated by Django 5.2.4 on 2025-08-18 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='min_quantity',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
    ]
