# Generated by Django 5.2.4 on 2025-09-01 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventoryitem_min_quantity'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailystockdata',
            unique_together={('product', 'date', 'voucher_type', 'inwards_quantity', 'outwards_quantity', 'closing_quantity')},
        ),
    ]
