# Generated by Django 5.2.4 on 2026-06-19 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_dashboard', '0010_customerunit_customerunitmembership'),
        ('inventory', '0009_purchaseorderstage_purchaseordertracking_and_more'),
        ('proforma_invoice', '0007_remove_proformapricechangerequest_requested_product_prices_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proformastockshortagerequest',
            name='shortage_details',
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='final_invoice_number',
            field=models.CharField(blank=True, help_text='The official Tax Invoice number generated at dispatch', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='proformastockshortagerequest',
            name='available_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proformastockshortagerequest',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.inventoryitem'),
        ),
        migrations.AddField(
            model_name='proformastockshortagerequest',
            name='requested_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='proformastockshortagerequest',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_requests', to='proforma_invoice.proformainvoice'),
        ),
        migrations.CreateModel(
            name='CreditPeriodOverdueByPassRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_approved_by', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_dashboard.customer')),
                ('proforma_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_approvals', to='proforma_invoice.proformainvoice')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_requests_made', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
