# Generated by Django 5.2.4 on 2026-06-22 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proforma_invoice', '0008_remove_proformastockshortagerequest_shortage_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proformainvoice',
            name='final_invoice_number',
        ),
        migrations.AddField(
            model_name='proformapricechangerequest',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, help_text='Snapshot of quantity at time of request', null=True),
        ),
    ]
