# Generated by Django 5.2.4 on 2026-06-22 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proforma_invoice', '0009_remove_proformainvoice_final_invoice_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proformapricechangerequest',
            name='review_duration_seconds',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
