# Generated by Django 5.2.4 on 2026-06-22 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proforma_invoice', '0010_proformapricechangerequest_review_duration_seconds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proformapricechangerequest',
            name='review_duration_seconds',
        ),
    ]
