# Generated by Django 5.2.4 on 2026-07-10 11:32

import django.db.models.deletion
import proforma_invoice.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_dashboard', '0011_alter_customercreditprofile_credit_period_days'),
        ('inventory', '0009_purchaseorderstage_purchaseordertracking_and_more'),
        ('proforma_invoice', '0011_remove_proformapricechangerequest_review_duration_seconds'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationMaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('validity', models.DateTimeField(default=proforma_invoice.models.validity_default)),
                ('created_by', models.CharField(default='Oblu', max_length=255)),
                ('is_price_altered', models.BooleanField(default=False)),
                ('courier_mode', models.CharField(choices=[('surface', 'Surface'), ('air', 'Air')], default='surface', max_length=10)),
                ('is_converted_to_proforma', models.BooleanField(default=False, help_text='True if this quotation was converted to a Proforma Invoice')),
                ('converted_at', models.DateTimeField(blank=True, help_text='Timestamp when converted to PI', null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_dashboard.customer')),
                ('shipping_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_shipping', to='customer_dashboard.customer')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.AddField(
            model_name='proformapricechangerequest',
            name='quotation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_requests', to='proforma_invoice.quotationmaker'),
        ),
        migrations.AddField(
            model_name='proformaremark',
            name='quotation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remarks', to='proforma_invoice.quotationmaker'),
        ),
        migrations.AddField(
            model_name='proformastockshortagerequest',
            name='quotation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_requests', to='proforma_invoice.quotationmaker'),
        ),
        migrations.CreateModel(
            name='QuotationMakerItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('customer_name_snapshot', models.CharField(blank=True, max_length=255, null=True)),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('requested_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('current_msrp', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('current_courier_charge', models.DecimalField(decimal_places=2, default=0.0, help_text='Current - courier', max_digits=10)),
                ('requested_courier_charge', models.DecimalField(decimal_places=2, default=0.0, help_text='Requested - courier', max_digits=10)),
                ('made_by', models.CharField(blank=True, help_text='made-by', max_length=255, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventoryitem')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='proforma_invoice.quotationmaker')),
            ],
        ),
    ]
