# Generated by Django 5.2.4 on 2026-07-14 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proforma_invoice', '0012_quotationmaker_proformapricechangerequest_quotation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proformapricechangerequest',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_requests', to='proforma_invoice.proformainvoice'),
        ),
        migrations.AlterField(
            model_name='proformaremark',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remarks', to='proforma_invoice.proformainvoice'),
        ),
        migrations.AlterField(
            model_name='proformastockshortagerequest',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_requests', to='proforma_invoice.proformainvoice'),
        ),
    ]
