# Generated by Django 6.1 on 2026-09-02 06:31

import django.db.models.deletion
import proforma_invoice.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proforma_invoice', '0013_alter_proformapricechangerequest_invoice_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tracking_url', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='proformastockshortagerequest',
            name='quotation',
        ),
        migrations.AlterField(
            model_name='proformastockshortagerequest',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_requests', to='proforma_invoice.proformainvoice'),
        ),
        migrations.CreateModel(
            name='DispatchRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('waiting_for_packing', 'Waiting For Packing'), ('packed_awaiting_approval', 'Packed - Awaiting Approval'), ('packing_approved', 'Packing Approved'), ('dispatched_by_warehouse', 'Dispatched By Warehouse'), ('completed', 'Completed'), ('packing_rejected', 'Packing Rejected'), ('cancelled', 'Cancelled')], default='requested', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_request', to='proforma_invoice.proformainvoice')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('shipment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='proforma_invoice.shipmentmethod')),
            ],
        ),
        migrations.CreateModel(
            name='DispatchRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('dispatch_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remarks', to='proforma_invoice.dispatchrequest')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DispatchPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=proforma_invoice.models.dispatch_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('dispatch_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='proforma_invoice.dispatchrequest')),
            ],
        ),
        migrations.CreateModel(
            name='DispatchInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to=proforma_invoice.models.dispatch_invoice_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('dispatch_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_file', to='proforma_invoice.dispatchrequest')),
            ],
        ),
        migrations.CreateModel(
            name='DispatchStateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=50)),
                ('to_status', models.CharField(max_length=50)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('dispatch_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='proforma_invoice.dispatchrequest')),
            ],
            options={
                'ordering': ['changed_at'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseDispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docket_number', models.CharField(max_length=100)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('dispatch_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='proforma_invoice.dispatchrequest')),
                ('dispatched_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
