# Generated by Django 6.1 on 2026-09-19 04:21

import django.db.models.deletion
import proforma_invoice.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proforma_invoice', '0014_shipmentmethod_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchstatehistory',
            name='event_type',
            field=models.CharField(choices=[('status', 'Status Change'), ('docket', 'Docket Change')], default='status', max_length=20),
        ),
        migrations.AlterField(
            model_name='dispatchstatehistory',
            name='from_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dispatchstatehistory',
            name='to_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='DocketPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=proforma_invoice.models.docket_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('warehouse_dispatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='proforma_invoice.warehousedispatch')),
            ],
        ),
    ]
