# Generated by Django 5.2.4 on 2025-08-05 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0004_quotationitem_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='quotation',
            name='created_by',
            field=models.CharField(choices=[('Bhavya Bhardwaj', 'Bhavya'), ('Ankush', 'Ankush'), ('Nimit Sharma', 'Nimit'), ('Aman Poddar', 'Aman')], default='Bhavya', max_length=255),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=2550)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'address')},
            },
        ),
    ]
